Traceback (most recent call last):
  File "/Users/summer/venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/summer/venv/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/summer/venv/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/summer/venv/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/summer/venv/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/summer/venv/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/summer/venv/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xml_data = objectify.parse('generation_fuel_type_multiday.xml')  # Parse XML data
root = xml_data.getroot()
lst = []
data = []
cols = []

for i in root.getchildren():
  if str(type(i)) == "<class 'lxml.objectify.ObjectifiedElement'>":
    lst.append(i)
    cols.append(i.attrib['Series'])

for child in lst:
  tmp = child.getchildren()
  arr = []
  for subchild in tmp:
    val = subchild.getchildren()
    arr.append(val[0])
  data.append(arr)

print([len(data[0]), len(data[1]), len(data[2])])

for i in range(len(data)):
  data[i] = data[i][:-5]
  data[i] = list(map(float, data[i]))


df = pd.DataFrame(data).T
cols = ["Supply_" + name for name in cols]
df.columns = cols
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m xml_data [38;5;241m=[39m [43mobjectify[49m[38;5;241;43m.[39;49m[43mparse[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mgeneration_fuel_type_multiday.xml[39;49m[38;5;124;43m'[39;49m[43m)[49m  [38;5;66;03m# Parse XML data[39;00m
[1;32m      2[0m root [38;5;241m=[39m xml_data[38;5;241m.[39mgetroot()
[1;32m      3[0m lst [38;5;241m=[39m []

File [0;32msrc/lxml/objectify.pyx:2044[0m, in [0;36mlxml.objectify.parse[0;34m()[0m

File [0;32msrc/lxml/etree.pyx:3541[0m, in [0;36mlxml.etree.parse[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:1879[0m, in [0;36mlxml.etree._parseDocument[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:1905[0m, in [0;36mlxml.etree._parseDocumentFromURL[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:1808[0m, in [0;36mlxml.etree._parseDocFromFile[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:1180[0m, in [0;36mlxml.etree._BaseParser._parseDocFromFile[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:618[0m, in [0;36mlxml.etree._ParserContext._handleParseResultDoc[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:728[0m, in [0;36mlxml.etree._handleParseResult[0;34m()[0m

File [0;32msrc/lxml/parser.pxi:655[0m, in [0;36mlxml.etree._raiseParseError[0;34m()[0m

[0;31mOSError[0m: Error reading file 'generation_fuel_type_multiday.xml': failed to load external entity "generation_fuel_type_multiday.xml"
OSError: Error reading file 'generation_fuel_type_multiday.xml': failed to load external entity "generation_fuel_type_multiday.xml"

